/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package docker.test.server;

public class App {
    public static void main(String[] args) {
        Runtime runtime = Runtime.getRuntime();

        int availableProcessors = runtime.availableProcessors();
        long totalMemory = runtime.totalMemory();
        long maxMemory = runtime.maxMemory();
        long freeMemory = runtime.freeMemory();

        System.out.println("Version " + System.getProperty("java.version"));

        System.out.println("Processors: " + availableProcessors);

        System.out.println("Heap size: " + totalMemory / Math.pow(2, 20) + "/" + maxMemory / Math.pow(2, 20));
        System.out.println("Free heap memory size : " + freeMemory / Math.pow(2, 20));
    }
}
